// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzrfmgkaqkfxxnyofbpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cmZtZ2thcWtmeHhueW9mYnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzI1OTIsImV4cCI6MjA2NDQwODU5Mn0.QDGVdWR_H6nWbd7vkzbbI2-BbOZBcWNQ7kgiZAmkpXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});